---
apiVersion: v1
kind: Pod
metadata:
  name: amd-gpu-rocm
  namespace: buildkit
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - orla
  containers:
    - name: amd-gpu
      image: rocm/pytorch:rocm6.2.1_ubuntu22.04_py3.10_pytorch_release_2.1.2
      imagePullPolicy: IfNotPresent
      securityContext:
        seccompProfile:
          type: Unconfined
        capabilities:
          add: ["SYS_ADMIN"]
      resources:
        limits:
          cpu: '8'
          memory: 64Gi
      volumeMounts:
        - name: dev-kfd
          mountPath: /dev/kfd
        - name: dev-dri
          mountPath: /dev/dri
  volumes:
    - name: dev-kfd
      hostPath:
        path: /dev/kfd
    - name: dev-dri
      hostPath:
        path: /dev/dri
  restartPolicy: Never