---
apiVersion: v1
kind: Pod
metadata:
  name: buildkit
  namespace: buildkit
#   annotations:
#     container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
# see buildkit/docs/rootless.md for caveats of rootless mode
spec:
  containers:
    - name: buildkit
      image: moby/buildkit:master-rootless
      args:
        - '--oci-worker-no-process-sandbox'
      securityContext:
        # Needs Kubernetes >= 1.19
        seccompProfile:
          type: Unconfined
        # To change UID/GID, you need to rebuild the image
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        # Dockerfile has `VOLUME /home/user/.local/share/buildkit` by default too,
        # but the default VOLUME does not work with rootless on Google's Container-Optimized OS
        # as it is mounted with `nosuid,nodev`.
        # https://github.com/moby/buildkit/issues/879#issuecomment-1240347038
        - name: buildkit
          mountPath: /home/user/.local/share/buildkit
  volumes:
    - name: buildkit
      emptyDir: {}