apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: buildkit
stringData:
  config.json: ENC[AES256_GCM,data:bDnkMOQquLF7c9pmwJ4+e/BXK5AAErngmY61kpPNJNgNmTmR4MbslX7dAZ+lvm6bU3x0fnnn8tXsjH2eW67al2eOoO2pbau/K9faDnQ8sibsxCP9m3h2geFrMrPVZVKft1hDyESpLScQot0LtPUDY9l6tViklg==,iv:uyR2ES/LaYV2DO9fKyYvs7yTp95wxPOd+MdQiYEizgc=,tag:Cr4hEfDyD2UZ217t8Eynig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17jjqp30xfyqtgthtk2c0gwqd04yy4q35xn9s5l54ytkemps3w4uqevle9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVBBOEl4UmZCemxMQ2gz
        eHJoandBV1VIeG9CdzNOQ2RVeCtqLzFGMUZFCjM5elVXU2N3VW1rVng4aVVxYXUv
        UzJla3V6d3EycXova29QQXpGbmpBNTQKLS0tIHd3MzVHT2lTUVF6SmNKVnRuaVVs
        ekQ4MHo5MlpEUEd0TVBSNTl2M1hoc0kK5W/QgKCY5+SLPuOJR3XBHhWtlj/k1fM6
        STn1PNgW0ePh2pqsOqITK3+yQd0BKrG2FgRAvmTDh/ZgTAZHIbyO5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-29T10:00:08Z"
  mac: ENC[AES256_GCM,data:oJQtM2ZEDNyquddTFhjD/fzQn3i+Ab86eahGY3uTIv+tz7VRem3DILOdLkYV/5C2VTUNH2QIHkIpRWwzU2+5hLTJjA/vQAjN0mShV29Usr7lLbe36GfoKu23E0ctbkdaP4ysik+bx/wut3rVrf1tZxszbGO1ifalttVezCu3Wt4=,iv:rkrYQmMtI4d1m2svEHd1H5xmH0Ri9tQAR9iWBdKp70I=,tag:x6beE6X4O3EFId/fpKDB/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
