---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: temporal
  namespace: temporal
spec:
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
  interval: 1m
  ref:
    branch: main
  url: https://github.com/temporalio/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 12h
  url: https://go.temporal.io/helm-charts 
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  releaseName: temporal
  interval: 5m
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: HelmRepository
        name: temporal
  install:
    remediation:
      retries: 3