creation_rules:
  # Talos Data Encryption Key (DEK)
  - path_regex: ^talos/.*/*.enc.ya?ml$
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    mac_only_encrypted: true
    age: age157d58w2rqqcpfrmr6wnff8kztndmkpg3440l42aqwv6nt2x3xanq7a5ulv

  # Kubernetes Key Encryption Key (KEK)
  - path_regex: ^kubernetes/flux-system/sops-agekey.enc.ya?ml$
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    age: age1nrwpgjgtz7ark8czz32ecsap0wfryv2pnv97hndw8zkaau5vl5mspnx9dt

  # Kubernetes Data Encryption Key (DEK)
  - path_regex: ^kubernetes/.*/*.enc.ya?ml$
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    age: age1dckjxj0g9pd8fqa5w5dx6x3tc4yuuajjw5hv8rplav9nannc4qhq3mvhjt

stores:
  yaml:
    indent: 2
