creation_rules:
  # Kubernetes Key Encryption Key (KEK)
  - path_regex: ^kubernetes/flux-system/sops-agekey.enc.yaml$
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: age1nrwpgjgtz7ark8czz32ecsap0wfryv2pnv97hndw8zkaau5vl5mspnx9dt

  # Kubernetes Data Encryption Key (DEK)
  - path_regex: ^kubernetes/.*/*.enc.ya?ml$
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    age: age1dckjxj0g9pd8fqa5w5dx6x3tc4yuuajjw5hv8rplav9nannc4qhq3mvhjt

  # Talos Data Encryption Key (DEK)
  # - path_regex: ^talos/.*\.enc\.ya?ml$
  #   input_type: yaml
  #   encrypted_regex: "((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))"
  #   age: <age-key>

stores:
  yaml:
    indent: 2
