creation_rules:
    # IMPORTANT: Keep this rule first
  - path_regex: orla-mc.yaml
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    mac_only_encrypted: true
    age: age157d58w2rqqcpfrmr6wnff8kztndmkpg3440l42aqwv6nt2x3xanq7a5ulv

    # Fallthrough rule
  - path_regex: \.ya?ml$
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    age: age17jjqp30xfyqtgthtk2c0gwqd04yy4q35xn9s5l54ytkemps3w4uqevle9d

stores:
  yaml:
    indent: 2