---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    toolkit.fluxcd.io/deployment: infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: registry
spec:
  interval: 12h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
  namespace: registry
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
  install:
    remediation:
      retries: 3
  timeout: 10m
  interval: 10m
  releaseName: registry
  targetNamespace: registry
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  #       kubernetes.io/hostname: rondo
  #   exporter:
  #     tls:
  #       commonName: registry.cluster.internal
  #   portal:
  #     nodeSelector:
  #       kubernetes.io/hostname: rondo
  #   redis:
  #     internal:
  #       nodeSelector:
  #         kubernetes.io/hostname: rondo
  #   # service:
  #   #   type: ClusterIP
  #   # portal:
  #   #   image:
  #   #     debug: true
  #   # ingress:
  #   #   core:
  #   #     hostname: registry.cluster.internal
  #   #     annotations:
  #   #       kubernetes.io/ingress.class: nginx
  #   #       cert-manager.io/cluster-issuer: selfsigned
  #   #         debug: true
  #     controller:
  #       kubernetes.io/hostname: rondo
  #     server:
  #       image:
  #         debug: true
  #   ingress:
  #     core:
  #   #     tls: true
  #       hostname: registry.cluster.internal
  #   #     selfSigned: true
  #   nginx:
  #       debug: true
  #   registry:
  #       debug: true
  #   jobservice:
  # values:
  #   clusterDomain: cluster.internal
  #   adminPassword: JKyikIY9EjR2vBTR22nI9S
  #   externalURL: https://registry.cluster.internal
  #   logLevel: debug
  #   trivy:
  #     enabled: false
  #   # service:
  #   #   type: ClusterIP
  #   #   clusterIP: 10.96.0.50
  #   #   loadBalancerIP: 192.168.88.11
  #   core:
  #     nodeSelector:
  #       kubernetes.io/hostname: rondo
  #     image:
  #       debug: true
  #     tls: 
  #   #       enabled: true