---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 5m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # nameOverride: ingress-nginx
    # fullnameOverride: ingress-nginx
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      # hostAliases:
      #   - ip: 192.168.88.10
      #     hostnames: 
      #       - cluster.local
      #       - "*.cluster.local"
      networkPolicy:
        enabled: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: cluster.internal
      ingressClassResource:
        default: true
    defaultBackend:
      enabled: true
