---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.14.8
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/native
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system