---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    toolkit.fluxcd.io/deployment: infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/metrics-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    createNamespace: true
  interval: 5m
  releaseName: metrics-server
  targetNamespace: metrics-server
  values:
    defaultArgs:
      - '--cert-dir=/tmp'
      - '--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname'
      - '--kubelet-use-node-status-port'
      - '--kubelet-insecure-tls'
      - '--metric-resolution=15s'
    fullnameOverride: metrics-server
    nameOverride: metrics-server