---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-stack
  labels:
    toolkit.fluxcd.io/deployment: infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus-stack
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: prometheus-stack
spec:
  interval: 10m
  targetNamespace: infra
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    nameOverride: prometheus-stack
    grafana:
      persistence:
        enabled: true
        type: sts
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        size: 2Gi
        finalizers:
          - kubernetes.io/pvc-protection
    prometheusOperator:
      clusterDomain: cluster.internal
    prometheus:
      prometheusSpec:
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Retain
          whenScaled: Retain
