---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcontainer
  namespace: devcontainers
  labels:
    app: devcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcontainer
  template:
    metadata:
      labels:
        app: devcontainer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - orla
      containers:
        - name: devcontainer
          resources:
            limits:
              amd.com/gpu: 1
          image: registry.cluster.internal/library/rocm/dev-ubuntu-22.04:6.2.4-kobold
          imagePullPolicy: IfNotPresent
          workingDir: /workspace
          env:
            - name: HIP_VISIBLE_DEVICES
              value: '0'
            - name: HSA_OVERRIDE_GFX_VERSION
              value: 11.0.0
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: llama.cpp-sandbox
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: llama.cpp-sandbox
#   namespace: devcontainers
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 64Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: devcontainer
#   namespace: devcontainers
#   labels:
#     app: devcontainer
# spec:
#   selector:
#     app: devcontainer
#   type: ClusterIP