---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: temporal
  namespace: temporal
spec:
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
  interval: 1m
  ref:
    branch: main
  url: https://github.com/temporalio/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  releaseName: temporal
  interval: 5m
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: GitRepository
        name: temporal
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    server:
      replicaCount: 1
    cassandra:
      config:
        cluster_size: 1
    elasticsearch:
      replicas: 1
    prometheus:
      enabled: false
    grafana:
      enabled: false