---
apiVersion: v1
kind: Pod
metadata:
  name: buildkit
  namespace: buildkit
spec:
  hostAliases:
    - ip: 192.168.88.10
      hostnames:
        - registry.cluster.internal
  containers:
    - name: buildkit
      image: moby/buildkit:master
      env:
        - name: DOCKER_CONFIG
          value: /root/.docker
      command:
        - sh
        - -c
        - |
          echo "Updating CA certs"
          update-ca-certificates
          echo "Cloning podinfo"
          git clone https://github.com/stefanprodan/podinfo.git /workspace
          echo "Building podinfo"
          buildctl-daemonless.sh build \
            --frontend dockerfile.v0 \
            --local context=/workspace \
            --local dockerfile=/workspace \
            --opt filename=Dockerfile \
            --output type=image,name=registry.cluster.internal/library/podinfo:deleteme,push=true \
            --export-cache type=registry,ref=registry.cluster.internal/library/podinfo:buildcache,image-manifest=true \
            --import-cache type=registry,ref=registry.cluster.internal/library/podinfo:buildcache
      securityContext:
        privileged: true
      volumeMounts:
        # https://github.com/moby/buildkit/issues/879#issuecomment-1240347038
        - name: workspace
          mountPath: /workspace
        - name: registry-ca
          mountPath: /etc/ssl/certs/registry-ca.pem
          subPath: ca.crt
        - name: docker-config
          mountPath: /root/.docker
          readOnly: true
  volumes:
    - name: workspace
      emptyDir: {}
    - name: registry-ca
      configMap:
        name: registry-ca
    - name: docker-config
      secret:
        secretName: docker-config