---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/matejaputic/mateja.lol-gitops.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-stable-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.helm.sh/stable
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://bjw-s.github.io/helm-charts/
  timeout: 3m
