---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
resources:
  - ns.yaml
  - snapshot-controller-hr.yaml
  - volsync-hr.yaml
commonLabels:
  app.kubernetes.io/component: core
