---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
  namespace: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  targetNamespace: hoarder
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  valuesFrom:
    - targetPath: controllers.hoarder.containers.hoarder.env.NEXTAUTH_SECRET
      kind: Secret
      name: hoarder-secrets
      valuesKey: NEXTAUTH_SECRET
    - targetPath: controllers.hoarder.containers.hoarder.env.MEILI_MASTER_KEY
      kind: Secret
      name: hoarder-secrets
      valuesKey: MEILI_MASTER_KEY
    - targetPath: controllers.hoarder.containers.meilisearch.env.MEILI_MASTER_KEY
      kind: Secret
      name: hoarder-secrets
      valuesKey: MEILI_MASTER_KEY
  values:
    fullnameOverride: hoarder
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      hoarder:
        containers:
          hoarder:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.19.0@sha256:237430c1c8117ada68a2d6c37487e5c234a306f43c244670689e6cabd2cffce2
            env:
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              CRAWLER_VIDEO_DOWNLOAD: true
              DATA_DIR: /data
              INFERENCE_IMAGE_MODEL: llava
              INFERENCE_TEXT_MODEL: llama3.2:3b
              MEILI_ADDR: http://hoarder-meilisearch:7700
              NEXTAUTH_URL: hoarder.${SECRET_INTERNAL_DOMAIN}
              OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
              INFERENCE_JOB_TIMEOUT_SEC: 299
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 750Mi
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
              - "--headless"
              - "--no-sandbox"
              - "--disable-gpu"
              - "--disable-dev-shm-usage"
              - "--remote-debugging-address=0.0.0.0"
              - "--remote-debugging-port=9222"
              - "--hide-scrollbars"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                cpu: 200m
                memory: 300Mi
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.11.3@sha256:6f8f1fc29d1ff67b4d8d503bb4e0a69b55c8d42600decafde951344218193a27
            env:
              MEILI_NO_ANALYTICS: "true"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
              fsGroupChangePolicy: OnRootMismatch
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      hoarder:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: hoarder
        ports:
          http:
            port: 9222
      meilisearch:
        controller: hoarder
        ports:
          http:
            port: 7700
    ingress:
      hoarder:
        enabled: true
        annotations: {}
        hosts:
          - host: hoarder.${SECRET_INTERNAL_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: hoarder
                  port: http
        tls:
          - hosts:
              - hoarder.${SECRET_INTERNAL_DOMAIN}
    persistence:
      config:
        existingClaim: hoarder
        advancedMounts:
          hoarder:
            hoarder:
              - path: /data
                subPath: data
            meilisearch:
              - path: /meili_data
                subPath: meili_data
      cache:
        type: emptyDir
        advancedMounts:
          hoarder:
            hoarder:
              - path: /app/apps/web/.next/cache
