---
apiVersion: v1
kind: Secret
metadata:
  name: hoarder-secrets
  namespace: hoarder
stringData:
  NEXTAUTH_SECRET: AwhXX+yoIhihdP/5HBzMW0D+xv98DEktouhI6Nv3Fz9F6B3N
  MEILI_MASTER_KEY: CG5/XFrEg5tKl8mgHfU+Y0vwX3pfR3LveIZ1d09u/CnxZsxn
