---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/dashboard
  - ../base/temporal.io
  - dashboard-extras.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: dashboard-values.yaml
    target:
      kind: HelmRelease