---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hoarder
  # - ../base/podinfo
  # - ../base/dashboard
  # - ../base/temporal
  # - ../base/rsshub
  # - dashboard-extras.yaml
patches:
  []
  # - path: podinfo-values.yaml
  #   target:
  #     kind: HelmRelease
  #     namespace: podinfo
  # - path: dashboard-values.yaml
  #   target:
  #     kind: HelmRelease
  #     namespace: dashboard
  # - path: rsshub-values.yaml
  #   target:
  #     kind: HelmRelease
  #     namespace: rsshub
  # - path: temporal-values.yaml
  #   target:
  #     kind: HelmRelease
  #     namespace: temporal
