---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/dashboard
  # - ../base/temporal
  - dashboard-extras.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      namespace: podinfo
  - path: dashboard-values.yaml
    target:
      kind: HelmRelease
      namespace: dashboard
  # - path: temporal-values.yaml
  #   target:
  #     kind: HelmRelease
  #     namespace: temporal