---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  releaseName: temporal
  interval: 5m
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: HelmRepository
        name: temporal
  install:
    remediation:
      retries: 3
  values:
    server:
      replicaCount: 1
    cassandra:
      config:
        cluster_size: 1
    elasticsearch:
      replicas: 1
    prometheus:
      enabled: false
    grafana:
      enabled: false