---
apiVersion: v1
kind: Namespace
metadata:
  name: amd-gpu
  labels:
    toolkit.fluxcd.io/deployment: infra
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: amd-gpu-helm
  namespace: amd-gpu
spec:
  interval: 24h
  url: https://rocm.github.io/k8s-device-plugin/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: amd-gpu
spec:
  chart:
    spec:
      chart: amd-gpu
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-helm
  interval: 5m
  releaseName: amd-gpu
  targetNamespace: amd-gpu
  values:
    nfd:
      enabled: true
    labeller:
      enabled: true
    dp:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.31.0.0"
      resources: {}
    lbl:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        tag: "labeller-1.31.0.0"
      resources: {}
    imagePullSecrets: []
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    node_selector_enabled: false
    node_selector:
      feature.node.kubernetes.io/pci-0300_1002.present: "true"
      kubernetes.io/arch: amd64