---
apiVersion: v1
kind: Namespace
metadata:
  name: jfrog
  labels:
    toolkit.fluxcd.io/deployment: infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jfrog
  namespace: jfrog
spec:
  interval: 12h
  url: https://charts.jfrog.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jfrog
  namespace: jfrog
spec:
  chart:
    spec:
      chart: jfrog
      sourceRef:
        kind: HelmRepository
        name: jfrog
  install:
    remediation:
      retries: 3
  timeout: 10m
  interval: 10m
  releaseName: jfrog
  targetNamespace: jfrog
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values: