---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amd-gpu-storage
  namespace: amd-gpu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: openebs-hostpath