---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      hoarder:
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.19.0@sha256:237430c1c8117ada68a2d6c37487e5c234a306f43c244670689e6cabd2cffce2
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://hoarder-meilisearch:7700
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              NEXTAUTH_URL: https://hoarder.cluster.internal
            envFrom: &envFrom
              - secretRef:
                  name: hoarder-secret
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 750Mi
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.10.3@sha256:9d1b9b02fe6c68f60b54ce40092d8078f051b9341c400c90f907607636b7c9c1
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: hoarder
        ports:
          http:
            port: 9222
      meilisearch:
        controller: hoarder
        ports:
          http:
            port: 7700
    ingress:
      app:
        className: external
        hosts:
          - host: "{{ .Release.Name }}.cluster.internal"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: config-hoarder
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: data
            meilisearch:
              - path: /meili_data
                subPath: meili_data
